name: Feedback
description: Form to leave feedback regarding the GeoQuiz site
title: "[FEEDBACK] "
labels: ["feedback"]
assignees:
  - mrhrobertson
body:
- type: dropdown
  id: experience
  attributes:
    label: How would you rate the user experience of GeoQuiz?
    options:
      - Enjoyable
      - Usable
      - Needs improvement
      - Unusable
      - Unenjoyable
    validations:
      required: true
- type: dropdown
  id: design
  attributes:
    label: How would you rate the design of GeoQuiz?
    options:
      - Enjoyable
      - Usable
      - Needs improvement
      - Unusable
      - Unenjoyable
    validations:
      required: true
- type: dropdown
  id: recommend
  attributes:
    label: On a scale of 1-10, how likely would you recommend GeoQuiz to a friend?
    options:
      - 10 (Extremely likely)
      - 9
      - 8
      - 7
      - 6
      - 5 (Maybe, maybe not)
      - 4
      - 3
      - 2
      - 1 (Would not recommend)
    validations:
      required: true
- type: textarea
  id: written_feedback
  attributes:
    label: Do you have any additional feedback you would like to give? Leave this blank if this is not the case.
